@url = https://8080-marcoweb-securitytutori-9jmfkt0ko87.ws-us118.gitpod.io
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGQVRFQyBBUEkiLCJzdWIiOiJ0ZXN0ZSIsImV4cCI6MTc0NTk2NjgxNX0.SGCT_HfN2sxn-O5-FRLnk6b-8js-Nh6sfaE6qtAOy0o

GET {{url}}/protected
Authorization:  Bearer {{token}}